### ISSUE TITLE
Pink frame instead of pink rectangle?

### ISSUE THREAD

**Issue by fiona789** [perceptron8/pinky.ext#42] opened 2018-06-11 14:45 UTC
Very cool app, but now we don't see how the collected items look. Ever :)
Maybe it's possible to use only frame around the objects instead of full colored rectangle?
Thanks )

**Comment by perceptron8** [comment] 2018-06-11 15:10
Thanks! :) Unfortunately, this is not possible. I had numerous problems with redirection to servers outside Ubisoft CDN - because of that, one can't just host and use customized images. Also note that switching to frames only would make collectibles much harder to find for most people. It's not easy to satisfy everyone. I hope that you will find Pinky useful anyway ;)

**Comment by perceptron8** [comment] 2018-06-11 15:12
Duplicate of #1

**Closed by perceptron8** 2018-06-11 15:12 UTC
Labels: status:duplicate, type:enhancement
