### ISSUE TITLE
problem with opera

### ISSUE THREAD

**Issue by gemstern** [perceptron8/pinky.ext#58] opened 2019-07-09 12:01 UTC
Since 2 days pinky will not show all items. It shows about 10, all others not. Also not for ATs. I have already re-installed, cleared cache, running cleanmymac etc.
What can I do?
I'm using Opera on an Imac.

**Comment by perceptron8** [comment] 2019-07-09 15:43
Read. See https://github.com/perceptron8/pinky.ext/issues/57#issuecomment-509304885. Thank you.

**Comment by perceptron8** [comment] 2019-07-09 15:44
Duplicate of #55.

**Closed by perceptron8** 2019-07-09 15:43 UTC
