### ISSUE TITLE
does not work in opera from today

### ISSUE THREAD

**Issue by IronHiide** [perceptron8/pinky.ext#31] opened 2017-07-24 19:55 UTC
does not work in opera from today

**Comment by perceptron8** [comment] 2017-07-24 20:07
Duplicate of #29. See https://github.com/perceptron8/pinky.ext/issues/29#issuecomment-317458682. From *add-on metadata control panel*:

> Pinky v0.2.7 was submitted. Awaiting moderation.

Please be patient. It's up to Opera reviewers now. Usually it takes about 24 hours.

**Comment by perceptron8** [comment] 2017-07-25 14:44
> Pinky v0.2.7 on Opera Current: Published.

**Closed by perceptron8** 2017-07-25 14:44 UTC
Labels: status:duplicate, type:bug
