### ISSUE TITLE
Does not work after today GAME update 05.VII.2019

### ISSUE THREAD

**Issue by IronHiide** [perceptron8/pinky.ext#57] opened 2019-07-05 11:04 UTC
Does not work after today GAME update 05.VII.2019

**Comment by perceptron8** [comment] 2019-07-05 11:21
Duplicate of #55. Update Pinky to 0.4.2 and let me know if everything is alright.

**Comment by IronHiide** [comment] 2019-07-05 11:29
sorry for dump question where to download 0.4.2. installation ? I see here jusr 0.4.1 https://addons.opera.com/pl/extensions/details/pinky/

**Comment by srollsaver** [comment] 2019-07-05 11:34
hi there all 
i got the pinky 0.4.2 and working with firefox here also pinky isnt working ;-(

**Comment by perceptron8** [comment] 2019-07-05 11:37
@IronHiide Pinky for Opera is awaiting for moderation.
@srollsaver Have you tried clearing cache?

**Comment by srollsaver** [comment] 2019-07-05 11:38
did do that before yess but will try it again ;-)

**Comment by srollsaver** [comment] 2019-07-05 11:55
did do all of it still not working will try to remove pinky later on and reinstall it maybe that helps ;-)

**Comment by IronHiide** [comment] 2019-07-05 11:55
Works in CHROME :)

**Comment by srollsaver** [comment] 2019-07-05 11:56
yess i know chrome atm is the only one that it is working correctly in ;-)

**Comment by perceptron8** [comment] 2019-07-05 12:10
@srollsaver Could you test Pinky using https://www.tsotesting.com/en? It works for me...

**Comment by PiFour** [comment] 2019-07-05 16:01
Pinky works on test server, but not on real server (firefox)
I noticed that pinky was disabled in chrome after game update, maybe its related maybe not

**Comment by perceptron8** [comment] 2019-07-05 16:25
@PiFour Chrome was disabled because of new permissions. See diff between 0.4.1 and 0.4.2: [ f981691...5de2008](https://github.com/perceptron8/pinky.ext/compare/f981691b97f1f6ce64fe4a57d7271fed113ea660...5de200830a416285b41cb81c1d34bc7e88a46e6b#diff-4b1eb3dc48c4e16d49db5b42298fe654). Here's why:
> Starting from Chrome 72, an extension will be able to intercept a request only if it has host permissions to both the requested URL and the request initiator.
https://developer.chrome.com/extensions/webRequest

@PiFour What url does have TSO in your country? Is Pinky broken in Chrome too or is it just Firefox?

**Comment by criss20ster** [comment] 2019-07-05 16:25
Pinky dosent works for my in opera

**Comment by perceptron8** [comment] 2019-07-05 16:30
@criss20ster This is the last message I got:
> Pinky v0.4.2 was submitted. Awaiting moderation.
> perceptron8; Jul 4, 2019 5:58:33 PM UTC

Sometimes it takes 2 days. One time it took several weeks.

If you don't want to wait, you can use https://addons.opera.com/en/extensions/details/install-chrome-extensions/ to install Pinky v0.4.2 from [Chrome Web Store](https://chrome.google.com/webstore/detail/pinky/eijmklfnehnnkbfcoabieogaomookbna).

**Comment by criss20ster** [comment] 2019-07-05 16:42
> @criss20ster This is the last message I got:
> 
> > Pinky v0.4.2 was submitted. Awaiting moderation.
> > perceptron8; Jul 4, 2019 5:58:33 PM UTC
> 
> Sometimes it takes 2 days. One time it took several weeks.
> 
> If you don't want to wait, you can use https://addons.opera.com/en/extensions/details/install-chrome-extensions/ to install Pinky v0.4.2 from [Chrome Web Store](https://chrome.google.com/webstore/detail/pinky/eijmklfnehnnkbfcoabieogaomookbna).

Czyli co mam zainstalować na  operze jakieś rozszerzenie mini chrome i potem do opery ten pinky pod chroma ?

**Comment by PiFour** [comment] 2019-07-05 16:46
@perceptron8 
Its not working only in Firefox. Its fine with Chrome (didnt checked with other browsers)
https://www.thesettlersonline.com/en/play
I collected all collectables with chrome, cant test anymore :)

**Comment by perceptron8** [comment] 2019-07-05 17:02
@criss20ster Tak właśnie. Zainstaluj rozszerzenie "Install Chrome Extensions", a potem Pinky'ego dla Chrome.

**Comment by perceptron8** [comment] 2019-07-05 17:03
@PiFour Thanks! Give me some time please.

**Comment by perceptron8** [comment] 2019-07-05 17:19
It's all clear. There's no https://www.thesettlersonline.com/ in permissions! https://github.com/perceptron8/pinky.ext/blob/5de200830a416285b41cb81c1d34bc7e88a46e6b/manifest.json#L33-L48 

My bad. I'll fix this within minutes.

**Comment by perceptron8** [comment] 2019-07-05 17:41
This should be finally fixed in 0.4.3. Thank you for your patience. All of this mess happened because I wanted to replace "<all_urls>" with explicit list of URLs so you can feel a little bit safer.

Please let me know if everything is alright now.

**Comment by PiFour** [comment] 2019-07-05 19:17
Now its fine, checked it on friends island. Thank you!

**Comment by laurenwhelan** [comment] 2019-07-06 11:40
My Pinky is not working 2140 hrs AEST, 6th July 2019

**Comment by perceptron8** [comment] 2019-07-06 11:55
@laurenwhelan What browser are you using?

**Comment by IronHiide** [comment] 2019-07-06 12:29
when it will be working for opera ? :)

**Comment by perceptron8** [comment] 2019-07-06 12:34
@IronHiide See https://github.com/perceptron8/pinky.ext/issues/57#issuecomment-508810064. Just wait for 0.4.2 or 0.4.3 (both should work). I do not have any influence on how long it takes.

**Comment by laurenwhelan** [comment] 2019-07-06 12:39
Mozilla. I refuse to use chrome or Edge



Lauren Whelan

________________________________

**Comment by perceptron8** [comment] 2019-07-06 12:43
@laurenwhelan Which version of Pinky have you installed?

**Comment by ciarabelle** [comment] 2019-07-07 09:58
hi, when will it be updated for opera please? it should a few random reg collects - no event collects. and disappears after a bit.

**Comment by perceptron8** [comment] 2019-07-07 10:07
@ciarabelle hi, i don't know when it will be updated for Opera. I've submitted this 3 days ago. It's up to Opera Software now. See https://github.com/perceptron8/pinky.ext/issues/57#issuecomment-508812591.

**Comment by laurenwhelan** [comment] 2019-07-07 16:52
What about for firefox?



Lauren Whelan

________________________________

**Comment by perceptron8** [comment] 2019-07-07 16:56
@laurenwhelan See https://github.com/perceptron8/pinky.ext/issues/57#issuecomment-508923777

**Comment by laurenwhelan** [comment] 2019-07-07 16:58
> @laurenwhelan Which version of Pinky have you installed?

0.4.2

**Comment by perceptron8** [comment] 2019-07-07 17:03
@laurenwhelan I've introduced a permission related problem in 0.4.2 (see https://github.com/perceptron8/pinky.ext/issues/57#issuecomment-508820083 and https://github.com/perceptron8/pinky.ext/issues/57#issuecomment-508824739). It has been fixed 2 days ago. Please update to 0.4.3.

**Comment by laurenwhelan** [comment] 2019-07-07 17:07
wonderful thanks. It had said it was updated yesterday but now it has done it



Lauren Whelan

________________________________

**Comment by longjohn4263** [comment] 2019-07-08 15:56
How do I access 0.4.3? All I see is 0.4.1

**Comment by NetVamp1** [comment] 2019-07-08 16:36
Hall, ich kann Pinky nicht über den Chrome Store bei Opera installieren, 
gibt es eventuell Hilfestellung oder mache ich was falsch ?, Danke im voraus.
Greets
NetVamp

**Comment by perceptron8** [comment] 2019-07-08 16:51
**If you use Opera** you can:

1. Either: wait for Opera Software moderators to approve 0.4.3 which I happily submitted on Jul 5, 2019 at 5:31:24 PM UTC. There's nothing more I can do.
2. Or: remove Pinky installed from Opera add-ons and use https://addons.opera.com/en/extensions/details/install-chrome-extensions/ to install https://chrome.google.com/webstore/detail/pinky/eijmklfnehnnkbfcoabieogaomookbna.

**Comment by longjohn4263** [comment] 2019-07-08 17:08
Thank you!

**Comment by perceptron8** [comment] 2019-07-15 17:47
Good news! Pinky v0.4.3 for Opera is finally available.

> Status has changed for Pinky
> Pinky v0.4.3 on Opera Current:
> Published.

**Closed by perceptron8** 2019-07-15 17:47 UTC
Labels: status:duplicate, type:enhancement
