### ISSUE TITLE
Collectibles Summer Event 2019

### ISSUE THREAD

**Issue by daveissettled** [perceptron8/pinky.ext#56] opened 2019-07-05 08:43 UTC
Since latest hotfix, event collectibles are not highlighted.

**Comment by perceptron8** [comment] 2019-07-05 08:50
Possibly duplicate of #55? Which Pinky version do you use?

**Comment by daveissettled** [comment] 2019-07-05 09:03
Hi perceptron8, version is 0.4.1, i have also restarted browser several times with no result. have tried update button on extension also not worked. Others using Chrome report no issues but I am using Firefox... maybe an issue? Normal collects did show though.. strange.

**Comment by perceptron8** [comment] 2019-07-05 09:14
It should be 0.4.2. It has been published yesterday, check https://addons.mozilla.org/en-US/firefox/addon/_pinky/ if you like.

**Comment by daveissettled** [comment] 2019-07-05 09:14
OK, found out it was a simple cache issue, I had wiped cache before Firefox updated but not after. Wiped cache again and now appears to work. Thank you again for help and appologise.

**Closed** 2019-07-05 09:14 UTC
